paths:
  /api/product/:
    post:
      summary: Créer un nouveau produit
      tags: [Product]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [title, category_id, price]
              properties:
                title:
                  type: string
                description:
                  type: string
                category_id:
                  type: string
                price:
                  type: number
                color:
                  type: string
                composition:
                  type: string
                size:
                  type: string
                in_stock:
                  type: boolean
                stock:
                  type: integer
                weight_in_gr:
                  type: number
                is_promo:
                  type: boolean
                is_new:
                  type: boolean
                assetsData:
                  type: array
                  items:
                    type: object
      responses:
        '201':
          description: Produit créé avec succès
        '400':
          description: Données invalides ou catégorie inexistante
        '500':
          description: Erreur serveur
    get:
      summary: Récupérer tous les produits
      tags: [Product]
      responses:
        '200':
          description: Liste des produits
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
        '404':
          description: Aucun produit trouvé
        '500':
          description: Erreur serveur
    patch:
      summary: Mettre à jour un produit
      tags: [Product]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              properties:
                id:
                  type: integer
                title:
                  type: string
                description:
                  type: string
                category_id:
                  type: string
                price:
                  type: number
                color:
                  type: string
                composition:
                  type: string
                size:
                  type: string
                in_stock:
                  type: boolean
                stock:
                  type: integer
                weight_in_gr:
                  type: number
                is_promo:
                  type: boolean
                is_new:
                  type: boolean
                assetsData:
                  type: array
                  items:
                    type: object
      responses:
        '200':
          description: Produit mis à jour avec succès
        '400':
          description: Données invalides
        '404':
          description: Produit non trouvé
        '500':
          description: Erreur serveur
    delete:
      summary: Supprimer un produit
      tags: [Product]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Produit supprimé avec succès
        '400':
          description: ID invalide
        '404':
          description: Produit non trouvé
        '500':
          description: Erreur serveur
  /api/product/getById:
    get:
      summary: Récupérer un produit par ID
      tags: [Product]
      parameters:
        - in: query
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Produit trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  product:
                    $ref: '#/components/schemas/Product'
        '404':
          description: Produit non trouvé
        '500':
          description: Erreur serveur

  /api/product/review/{productId}:
    get:
      summary: Récupérer les avis d'un produit spécifique
      tags: [Product]
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
          description: ID du produit pour lequel récupérer les avis
      responses:
        '200':
          description: Avis du produit récupérés avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  reviews:
                    type: array
                    items:
                      $ref: '#/components/schemas/Review'
                    description: Liste des avis pour ce produit
                  count:
                    type: integer
                    description: Nombre total d'avis
                  average:
                    type: number
                    format: float
                    description: Note moyenne (arrondie à 1 décimale)
                    minimum: 1
                    maximum: 5
              examples:
                successResponse:
                  summary: Réponse avec avis
                  value:
                    reviews:
                      - id: 1
                        user_id: "507f1f77bcf86cd799439011"
                        product_id: "507f1f77bcf86cd799439012"
                        rating: 4
                        created_at: "2024-01-15T10:30:00Z"
                        updated_at: "2024-01-15T10:30:00Z"
                      - id: 2
                        user_id: "507f1f77bcf86cd799439013"
                        product_id: "507f1f77bcf86cd799439012"
                        rating: 5
                        created_at: "2024-01-16T14:20:00Z"
                        updated_at: "2024-01-16T14:20:00Z"
                    count: 2
                    average: 4.5
        '404':
          description: Produit non trouvé ou aucun avis trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                examples:
                  productNotFound:
                    summary: Produit non trouvé
                    value:
                      error: "Le produit n'a pas été trouvé"
                  noReviews:
                    summary: Aucun avis trouvé
                    value:
                      error: "Aucun avis trouvé pour ce produit"
        '500':
          description: Erreur serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: "Erreur lors de la récupération des avis du produit"
                  details:
                    type: string