paths:
  /api/productVariant/:
    post:
      summary: Créer un nouveau variant de produit
      tags: [ProductVariant]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [product_id, color_id, size_id, src]
              properties:
                product_id:
                  type: string
                  description: ID MongoDB du produit
                color_id:
                  type: string
                  description: ID MongoDB de la couleur
                size_id:
                  type: string
                  description: ID MongoDB de la taille
                src:
                  type: string
                stock:
                  type: integer
                available:
                  type: boolean
      responses:
        '201':
          description: Variant créé avec succès
        '400':
          description: Données invalides ou entités associées inexistantes
        '401':
          description: Non autorisé - Token manquant ou invalide
        '403':
          description: Accès refusé - Droits administrateur requis
        '500':
          description: Erreur serveur
    get:
      summary: Récupérer tous les variants de produits
      tags: [ProductVariant]
      responses:
        '200':
          description: Liste des variants
          content:
            application/json:
              schema:
                type: object
                properties:
                  variants:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductVariantWithPopulation'
        '404':
          description: Aucun variant trouvé
        '500':
          description: Erreur serveur
    patch:
      summary: Mettre à jour un variant de produit
      tags: [ProductVariant]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              properties:
                id:
                  type: integer
                product_id:
                  type: string
                color_id:
                  type: string
                size_id:
                  type: string
                src:
                  type: string
                stock:
                  type: integer
                available:
                  type: boolean
      responses:
        '200':
          description: Variant mis à jour avec succès
        '400':
          description: Données invalides
        '404':
          description: Variant non trouvé
        '500':
          description: Erreur serveur
    delete:
      summary: Supprimer un variant
      tags: [ProductVariant]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              properties:
                id:
                  type: integer
      responses:
        '200':
          description: Variant supprimé avec succès
        '400':
          description: ID manquant ou invalide
        '404':
          description: Variant non trouvé
        '500':
          description: Erreur serveur

  /api/productVariant/{productId}:
    get:
      summary: Récupérer les variants d'un produit par ID numérique
      tags: [ProductVariant]
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: integer
          description: ID numérique du produit
      responses:
        '200':
          description: Variants trouvés
          content:
            application/json:
              schema:
                type: object
                properties:
                  variants:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductVariantWithPopulation'
        '404':
          description: Aucun variant trouvé pour ce produit
        '500':
          description: Erreur serveur

components:
  schemas:
    ProductVariant:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        product_id:
          type: string
        color_id:
          type: string
        size_id:
          type: string
        src:
          type: string
        stock:
          type: integer
        available:
          type: boolean
        created_at:
          type: string
          format: date-time
          readOnly: true
        updated_at:
          type: string
          format: date-time
          readOnly: true
      required:
        - product_id
        - color_id
        - size_id
        - src

    ProductVariantWithPopulation:
      allOf:
        - $ref: '#/components/schemas/ProductVariant'
        - type: object
          properties:
            product_id:
              $ref: '#/components/schemas/Product'
            color_id:
              $ref: '#/components/schemas/ProductColor'
            size_id:
              $ref: '#/components/schemas/ProductSize'
