paths:
  /api/productSize/:
    post:
      summary: Créer une nouvelle taille de produit
      tags: [ProductSize]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [eu_size]
              properties:
                eu_size:
                  type: string
                  minLength: 2
                  maxLength: 10
                  description: Taille EU (ex: "42")
                label:
                  type: string
                  maxLength: 10
                  nullable: true
                  description: Label optionnel (ex: "M")
      responses:
        '201':
          description: Taille de produit créée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Taille de produit créée avec succès"
                  productSize:
                    $ref: '#/components/schemas/ProductSize'
        '400':
          description: Données invalides (format non conforme)
        '401':
          description: Non autorisé - Token manquant ou invalide
        '403':
          description: Accès refusé - Droits administrateur requis
        '500':
          description: Erreur serveur
    get:
      summary: Récupérer toutes les tailles de produits
      tags: [ProductSize]
      responses:
        '200':
          description: Liste des tailles de produits
          content:
            application/json:
              schema:
                type: object
                properties:
                  productSizes:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProductSize'
        '500':
          description: Erreur serveur

  /api/productSize/{productSizeId}:
    get:
      summary: Récupérer une taille de produit par ID numérique
      tags: [ProductSize]
      parameters:
        - in: path
          name: productSizeId
          required: true
          schema:
            type: integer
          description: ID numérique de la taille de produit
      responses:
        '200':
          description: Taille de produit trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  productSize:
                    $ref: '#/components/schemas/ProductSize'
        '404':
          description: Taille de produit non trouvée
        '500':
          description: Erreur serveur

components:
  schemas:
    ProductSize:
      type: object
      properties:
        id:
          type: integer
          description: ID unique de la taille de produit
          readOnly: true
        eu_size:
          type: string
          description: Taille EU
          minLength: 2
          maxLength: 10
        label:
          type: string
          description: Label optionnel
          maxLength: 10
          nullable: true
        created_at:
          type: string
          format: date-time
          description: Date de création
          readOnly: true
        updated_at:
          type: string
          format: date-time
          description: Date de dernière mise à jour
          readOnly: true
      required:
        - eu_size
