name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  # Job pour le client (frontend)
  client:
    name: Frontend Quality & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint

      - name: TypeScript check
        run: npm run typecheck

      - name: Build project
        run: npm run build

  # Job pour le serveur (backend)
  server:
    name: Backend Quality & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Check Prettier formatting
        run: npm run format:check

      - name: Run ESLint
        run: npm run lint

      - name: Build/Test server
        run: npm run build

  # Job de validation globale
  validation:
    name: Global Validation
    runs-on: ubuntu-latest
    needs: [client, server]

    steps:
      - name: All checks passed
        run: echo "✅ All quality checks and builds passed successfully!"
